// <auto-generated />
using System;
using LegelisteApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LegelisteApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512103322_NovogenUpgrade")]
    partial class NovogenUpgrade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LegelisteApp.Data.Models.DailyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnzahlSelektiert")
                        .HasColumnType("integer");

                    b.Property<int>("AnzahlVerendet")
                        .HasColumnType("integer");

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("integer");

                    b.Property<string>("Auslaufzeit")
                        .HasColumnType("text");

                    b.Property<string>("Bemerkungen")
                        .HasColumnType("text");

                    b.Property<int>("BodenEier")
                        .HasColumnType("integer");

                    b.Property<int>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Eier1Wahl")
                        .HasColumnType("integer");

                    b.Property<int>("Eier2Wahl")
                        .HasColumnType("integer");

                    b.Property<decimal>("Eigewicht")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FutterKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Knickeier")
                        .HasColumnType("integer");

                    b.Property<decimal>("Koerpergewicht")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Kontrollzeiten")
                        .HasColumnType("text");

                    b.Property<decimal>("Lichtstunden")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Schmutzeier")
                        .HasColumnType("integer");

                    b.Property<int>("StallId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("WasserLiter")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatorId");

                    b.HasIndex("StallId", "Date")
                        .IsUnique();

                    b.ToTable("DailyEntries");
                });

            modelBuilder.Entity("LegelisteApp.Data.Models.Stall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnfangsbestandTiere")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Einstallungsdatum")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Stalls");
                });

            modelBuilder.Entity("LegelisteApp.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LegelisteApp.Data.Models.DailyEntry", b =>
                {
                    b.HasOne("LegelisteApp.Data.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("LegelisteApp.Data.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegelisteApp.Data.Models.Stall", "Stall")
                        .WithMany("DailyEntries")
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Creator");

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("LegelisteApp.Data.Models.Stall", b =>
                {
                    b.Navigation("DailyEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
