// <auto-generated />
using System;
using LegelisteApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegelisteApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260812133503_UpdateDatabaseSchema")]
    partial class UpdateDatabaseSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegelisteApp.Data.Models.DailyEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedById")
                        .HasColumnType("int");

                    b.Property<string>("Auslaufzeit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Bemerkungen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CreatorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Eier1Wahl")
                        .HasColumnType("int");

                    b.Property<int>("Eier2Wahl")
                        .HasColumnType("int");

                    b.Property<decimal?>("Eigewicht")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FutterKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FutterlieferungKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Koerpergewicht")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("KontrollzeitenBis")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KontrollzeitenVon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LichtBis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LichtVon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StallId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Verluste")
                        .HasColumnType("int");

                    b.Property<decimal>("WasserLiter")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ZugaengeTiere")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("CreatorId");

                    b.HasIndex("StallId", "Date")
                        .IsUnique();

                    b.ToTable("DailyEntries");
                });

            modelBuilder.Entity("LegelisteApp.Data.Models.Stall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnfangsbestandTiere")
                        .HasColumnType("int");

                    b.Property<DateTime>("Einstallungsdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Stalls");
                });

            modelBuilder.Entity("LegelisteApp.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LegelisteApp.Data.Models.DailyEntry", b =>
                {
                    b.HasOne("LegelisteApp.Data.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("LegelisteApp.Data.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegelisteApp.Data.Models.Stall", "Stall")
                        .WithMany("DailyEntries")
                        .HasForeignKey("StallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Creator");

                    b.Navigation("Stall");
                });

            modelBuilder.Entity("LegelisteApp.Data.Models.Stall", b =>
                {
                    b.Navigation("DailyEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
